### ISSUE TITLE
Could not pass event PlayerInteractEvent to Greenhouses v5.7

### ISSUE THREAD

**Issue by krustymk** [tastybento/greenhouses#9]
26.02 20:01:20 [Server] ERROR **** THIS IS NOT AN ISSUE TO DO WITH PER WORLD PLUGINS ****
26.02 20:01:20 [Server] INFO Could not pass event PlayerInteractEvent to Greenhouses v5.7
26.02 20:01:20 [Server] INFO org.bukkit.event.EventException
26.02 20:01:20 [Server] INFO at us.Myles.PWP.TransparentListeners.PerWorldPluginLoader$1.execute(PerWorldPluginLoader.java:122) ~[?:?]
26.02 20:01:20 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at us.Myles.PWP.TransparentListeners.PWPRegisteredListener.callEvent(PWPRegisteredListener.java:30) [PerWorldPlugins%20v1.1.0.jar:?]
26.02 20:01:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at org.bukkit.craftbukkit.v1_11_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:232) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerInteractManager.a(PlayerInteractManager.java:444) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:904) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:37) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:1) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
26.02 20:01:20 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576) [spigot.jar:git-Spigot-d4f98a3-cb61ac0]
26.02 20:01:20 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
26.02 20:01:20 [Server] INFO Caused by: java.lang.NullPointerException

**Comment by tastybento** [comment]
Is there anything after the last line. As it stands, there's no actionable information in this report other than an error occurred.

When did the error occur? i.e., how is the error generated?

**Comment by krustymk** [comment]
That was the end of the error, just normal console jibberjabber after that. Player said they where just mining cobble...
Ill update when i know more

**Comment by tastybento** [comment]
Okay, let me know if you find anything more.
